language: csharp
solution: GEHS.Poc.sln
sudo: false

install:
  - apt-get install nunit-console
  - nuget restore GEHS.Poc.sln

script:
 - xbuild /p:Configuration=Release GEHS.Poc.sln
 - nunit-console ./GEHS.Poc.Test/bin/Release/GEHS.Poc.Test.dll
