language: csharp
solution: GEHS.Poc.sln
sudo: false

addons:
  apt:
    packages:
    - nunit-console
    
install:
  - nuget restore GEHS.Poc.sln

script:
 - xbuild /p:Configuration=Release GEHS.Poc.sln
 - nunit-console ./GEHS.Poc.Test/bin/Release/GEHS.Poc.Test.dll
 
